# Generated by Django 3.2.13 on 2022-06-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_merchant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstaff',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
